/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Faces_Manifest_Project;

import static Faces_Manifest_Project.Global.*;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdatepicker.JDateComponentFactory;
import org.jdatepicker.JDatePicker;

/**
 *
 * @author Edwin Mulwa
 */
public class VLResultsImport extends javax.swing.JPanel {

    // Declare Variables
    private static JDialog   m_dlgParent;
    private DataAccessClass dacFacilities;
    private List<String> locations;

    /**
     * Creates new form VLResultsImport
     */
    public VLResultsImport() throws SQLException, IOException, ParseException {
        
        initComponents();
        
        // Add Date Picker Control
        JDatePicker picker = new JDateComponentFactory().createJDatePicker();
        picker.setTextEditable(true);
        picker.setShowYearButtons(true);
        jpVLImportResults.add((JComponent) picker);

        picker.getModel().setYear(2010);
        picker.getModel().setMonth(1);
        //picker.getModel().setMonth(1);
        picker.getModel().setDay(15);
        picker.getModel().setSelected(true);

        
        // Load the facilities
        dacFacilities = new DataAccessClass();
        cboFacility.removeAllItems();
        locations = new ArrayList<String>();
        locations = dacFacilities.getLocations();
        
        for(String facility : locations)
        {
            cboFacility.addItem(facility);
        }
        
        // Preset the result option type i.e. AMPATH or MS Excel
        resultOption = 0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgImportSources = new javax.swing.ButtonGroup();
        utilDateModel = new org.jdatepicker.impl.UtilDateModel();
        sqlDateModel = new org.jdatepicker.impl.SqlDateModel();
        utilCalendarModel = new org.jdatepicker.impl.UtilCalendarModel();
        jDatePickerUtil = new org.jdatepicker.util.JDatePickerUtil();
        jDateComponentFactory = new org.jdatepicker.JDateComponentFactory();
        dateComponentFormatter = new org.jdatepicker.impl.DateComponentFormatter();
        jpVLImportResults = new javax.swing.JPanel();
        rbAMPATH = new javax.swing.JRadioButton();
        rbExcel = new javax.swing.JRadioButton();
        jpAmpath = new javax.swing.JPanel();
        lblLocation = new javax.swing.JLabel();
        cboFacility = new javax.swing.JComboBox();
        lblStartDate = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        dptStartDate = new org.jdesktop.swingx.JXDatePicker();
        dptEndDate = new org.jdesktop.swingx.JXDatePicker();
        jpExcel = new javax.swing.JPanel();
        lblSelectFile = new javax.swing.JLabel();
        txtSelectFile = new javax.swing.JTextField();
        btnSelectFile = new javax.swing.JButton();
        btnFetch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setName("VLResultsImport"); // NOI18N
        setPreferredSize(new java.awt.Dimension(586, 344));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpVLImportResults.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Source", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        bgImportSources.add(rbAMPATH);
        rbAMPATH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbAMPATH.setSelected(true);
        rbAMPATH.setText("AMPATH Website");
        rbAMPATH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAMPATHActionPerformed(evt);
            }
        });

        bgImportSources.add(rbExcel);
        rbExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbExcel.setText("MS Excel File");
        rbExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExcelActionPerformed(evt);
            }
        });

        jpAmpath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLocation.setText("Facility");

        cboFacility.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFacility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFacilityActionPerformed(evt);
            }
        });

        lblStartDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStartDate.setText("Start Date");

        lblEndDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEndDate.setText("End Date");

        dptStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dptStartDateActionPerformed(evt);
            }
        });

        dptEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dptEndDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAmpathLayout = new javax.swing.GroupLayout(jpAmpath);
        jpAmpath.setLayout(jpAmpathLayout);
        jpAmpathLayout.setHorizontalGroup(
            jpAmpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAmpathLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAmpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAmpathLayout.createSequentialGroup()
                        .addComponent(lblLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addGap(66, 66, 66)
                        .addComponent(lblStartDate)
                        .addGap(83, 83, 83))
                    .addGroup(jpAmpathLayout.createSequentialGroup()
                        .addComponent(cboFacility, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(dptStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(jpAmpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAmpathLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblEndDate))
                    .addGroup(jpAmpathLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(dptEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jpAmpathLayout.setVerticalGroup(
            jpAmpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAmpathLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAmpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAmpathLayout.createSequentialGroup()
                        .addGroup(jpAmpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAmpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpAmpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dptStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dptEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpAmpathLayout.createSequentialGroup()
                        .addComponent(lblEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)))
                .addGap(24, 24, 24))
        );

        jpExcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSelectFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSelectFile.setText("Select Source File");

        txtSelectFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSelectFile.setEnabled(false);
        txtSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectFileActionPerformed(evt);
            }
        });

        btnSelectFile.setText("Select");
        btnSelectFile.setEnabled(false);
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpExcelLayout = new javax.swing.GroupLayout(jpExcel);
        jpExcel.setLayout(jpExcelLayout);
        jpExcelLayout.setHorizontalGroup(
            jpExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExcelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpExcelLayout.createSequentialGroup()
                        .addComponent(lblSelectFile)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpExcelLayout.createSequentialGroup()
                        .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnSelectFile)))
                .addContainerGap())
        );
        jpExcelLayout.setVerticalGroup(
            jpExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExcelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpVLImportResultsLayout = new javax.swing.GroupLayout(jpVLImportResults);
        jpVLImportResults.setLayout(jpVLImportResultsLayout);
        jpVLImportResultsLayout.setHorizontalGroup(
            jpVLImportResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVLImportResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVLImportResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAmpath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpVLImportResultsLayout.createSequentialGroup()
                        .addGroup(jpVLImportResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAMPATH)
                            .addComponent(rbExcel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpVLImportResultsLayout.setVerticalGroup(
            jpVLImportResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVLImportResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAMPATH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAmpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jpVLImportResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 566, 280));

        btnFetch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFetch.setText("Fetch");
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });
        add(btnFetch, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 300, -1, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rbExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExcelActionPerformed

        // Enable/Disable controls
        txtSelectFile.setEnabled(true);
        btnSelectFile.setEnabled(true);
        cboFacility.setEnabled(false);
      //  txtStartDate.setEnabled(false);
      //  txtEndDate.setEnabled(false);
        dptStartDate.setEnabled(false);
        dptEndDate.setEnabled(false);
        
        // Preset the result option type i.e. AMPATH or MS Excel
        resultOption = 1;
        
    }//GEN-LAST:event_rbExcelActionPerformed

    private void txtSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectFileActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        try {

            // Cancel the importation
            cancelImport = true;
            
            // Close the form
            m_dlgParent.setVisible(false);

        }
        catch(Exception exError){
            exError.printStackTrace();
        }
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed

            // Open the source file with VL results and load patients info into arraylist
            JFileChooser excelFile = new JFileChooser();
            excelFile.showOpenDialog(null);
            dataFile = excelFile.getSelectedFile();
            txtSelectFile.setText(dataFile.getPath());
            
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void rbAMPATHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAMPATHActionPerformed

        // Enable/Disable controls
        txtSelectFile.setEnabled(false);
        btnSelectFile.setEnabled(false);
        cboFacility.setEnabled(true);
      // txtStartDate.setEnabled(true);
       // txtEndDate.setEnabled(true);
         dptStartDate.setEnabled(true);
        dptEndDate.setEnabled(true);
        
        // Preset the result option type i.e. AMPATH or MS Excel
        resultOption = 0;
        
    }//GEN-LAST:event_rbAMPATHActionPerformed

    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed

        try {

            // Set the global parameters based on the selections
            if(resultOption == 0){
                
                // AMPATH was selected. Validate the entries
                 if(dptStartDate.getDate().toString().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Please specify Start Date!");
                    return;
                }
                  if(dptEndDate.getDate().toString().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Please specify End Date!");
                    return;
                }
                  /*
                if(txtStartDate.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Please specify Start Date!");
                    return;
                }
                
                if(txtEndDate.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Please specify End Date!");
                    return;
                }
                */
                
                // Set the values
               
                // Rugut added 29/11/2016 datepicker code
                 Date startDate = (Date) dptStartDate.getDate();
                 Date endDate = (Date) dptEndDate.getDate();
                 DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                // String reportDate = df.format(startDate);
                vlImportStartDate =  df.format(startDate);//txtStartDate.getText();
                vlImportEndDate = df.format(endDate);//txtEndDate.getText();
                //vlImportStartDate =  txtStartDate.getText();
                //vlImportEndDate = txtEndDate.getText();
                importFacility = cboFacility.getSelectedItem().toString();
                
            }
            else {
                
            }
            
            // Cancel the importation
            cancelImport = false;
            
            // Close the form
            m_dlgParent.setVisible(false);

        }
        catch(Exception exError){
            exError.printStackTrace();
        }
        
    }//GEN-LAST:event_btnFetchActionPerformed

    private void cboFacilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFacilityActionPerformed

        // Store the selected facility
//        importFacility = cboFacility.getSelectedItem().toString();
        
    }//GEN-LAST:event_cboFacilityActionPerformed

    private void dptStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dptStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dptStartDateActionPerformed

    private void dptEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dptEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dptEndDateActionPerformed

    public void doModal(JDialog dlgParent){
        
        try {
            
            m_dlgParent = dlgParent;
            m_dlgParent.setContentPane(this);
            m_dlgParent.pack();
            m_dlgParent.setLocationRelativeTo(null);
            m_dlgParent.setVisible(true);
            m_dlgParent.dispose();

        }
        catch(Exception exError){
            exError.printStackTrace();
        }          
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgImportSources;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFetch;
    private javax.swing.JButton btnSelectFile;
    public static javax.swing.JComboBox cboFacility;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter;
    private org.jdesktop.swingx.JXDatePicker dptEndDate;
    private org.jdesktop.swingx.JXDatePicker dptStartDate;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil;
    private javax.swing.JPanel jpAmpath;
    private javax.swing.JPanel jpExcel;
    private javax.swing.JPanel jpVLImportResults;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblSelectFile;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JRadioButton rbAMPATH;
    private javax.swing.JRadioButton rbExcel;
    private org.jdatepicker.impl.SqlDateModel sqlDateModel;
    private javax.swing.JTextField txtSelectFile;
    private org.jdatepicker.impl.UtilCalendarModel utilCalendarModel;
    private org.jdatepicker.impl.UtilDateModel utilDateModel;
    // End of variables declaration//GEN-END:variables
}
